// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuhY0zBAP3PJ7N6tgs8JbiblVL5NJNwAg',
    appId: '1:685599255644:web:9017a82a75c5aec830ca99',
    messagingSenderId: '685599255644',
    projectId: 'chatty-33d13',
    authDomain: 'chatty-33d13.firebaseapp.com',
    storageBucket: 'chatty-33d13.appspot.com',
    measurementId: 'G-YLT43C5F65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCx1v4m8R2WF1_d75GXZb9i_GxJb7Me8s',
    appId: '1:685599255644:android:8ffb75813937a44c30ca99',
    messagingSenderId: '685599255644',
    projectId: 'chatty-33d13',
    storageBucket: 'chatty-33d13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaAAou7VcHQEmyyLFSGLhOJt6oVvDAmo',
    appId: '1:685599255644:ios:4a69028d52b13f9830ca99',
    messagingSenderId: '685599255644',
    projectId: 'chatty-33d13',
    storageBucket: 'chatty-33d13.appspot.com',
    iosClientId: '685599255644-iujo8c3b7a22navoht5hafuq6kk096j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiaAAou7VcHQEmyyLFSGLhOJt6oVvDAmo',
    appId: '1:685599255644:ios:4a69028d52b13f9830ca99',
    messagingSenderId: '685599255644',
    projectId: 'chatty-33d13',
    storageBucket: 'chatty-33d13.appspot.com',
    iosClientId: '685599255644-iujo8c3b7a22navoht5hafuq6kk096j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattyco',
  );
}
